Repository auth0/auth0-vue, pull requests merged in 2022-03, with the labels that each got.

#80 Support a guard without calling createAuthGuard
  EXAMPLES.md
  README.md
  __tests__/guard.test.ts
  playground/index.ts
  playground/router.ts
  src/global.ts
  src/guard.ts
  src/plugin.ts
Labels: CH: Added, review:medium

#85 [SDK-3164] Remove beta notices from repository
  .circleci/config.yml
  README.md
Labels: review:tiny

#94 [SDK-3165] Migrate Vue 2 quickstart
  README.md
  tutorial/create-api.png
  tutorial/universal-login.png
  tutorial/vue2-api.md
  tutorial/vue2-login.md
Labels: review:medium, documentation
